
HTM_DPANS = dpans.htm dpans1.htm dpans2.htm dpans3.htm dpans4.htm dpans5.htm \
 dpans6.htm dpans7.htm dpans8.htm dpans9.htm dpans10.htm dpans11.htm \
 dpans12.htm dpans13.htm dpans14.htm dpans15.htm dpans16.htm dpans17.htm \
 dpansa1.htm dpansa2.htm dpansa3.htm dpansa4.htm dpansa5.htm dpansa6.htm \
 dpansa7.htm dpansa8.htm dpansa9.htm dpansa10.htm dpansa11.htm dpansa12.htm \
 dpansa13.htm dpansa14.htm dpansa15.htm dpansa16.htm dpansa17.htm \
 dpansb.htm dpansc.htm dpansd.htm dpanse.htm dpansf.htm

RFI_DPANS = notes.htm rfilist.htm \
 a0001.htm a0002.htm a0003.htm a0004.htm a0005.htm a0006.htm a0007.htm

GIF_DPANS = left.gif right.gif up.gif

index:
	-ln -s dpans-x.htm index.html # dpans-x is not part of dpans!
	-cp ../../forth.css dpans.css

zip:
	zip -9 ../dpans94.zip \
	$(HTM_DPANS) $(RFI_DPANS) $(GIF_DPANS)
